### ISSUE TITLE
one-voip gdextension?

### ISSUE THREAD

**Issue by Pillber** [RevoluPowered/one-voip-godot-4#10]
I've been trying and failing miserably to get a voip system that I'm happy with using Godot and GodotSteam. Both the old godot-voip plugin for Godot 3 (which I updated myself for Godot 4) and Steam Voice either would get increasingly stuttery with more players connected or just had stutters in general respectively. I came across this project and it seems really promising.

In the README and demo folder, there seems to be references to a one-voip gdextension plugin, but there are no releases nor extension that I can find. Is this project still active? If so, is there a gdextension plugin like I expected, or do I have to compile myself?

**Comment by Topicranger** [comment]
I do not know the status of this project. However, the extension works, but you have to compile it yourself.
If you update the submodules (`git submodule update --remote`) and follow the build instructions, it should compile for Godot 4.2.

**Comment by marc-weber1** [comment]
Hi, I wanted to wait until all the bugs on linux are fixed before we made a release, but it works on windows (without a jitter buffer, yet). I will update it for godot 4.2 soon, and maybe put up a windows-only release?

**Comment by Pillber** [comment]
That would be really awesome! I'd like to get familiar with this plugin, and to be honest I am not very sure about my compilation skills. I'm working on windows, so windows only will work okay for me. Is it or is it not ready for Godot 4.2 though? marc-weber1 and Topicranger seem to be saying different things.

**Comment by marc-weber1** [comment]
https://github.com/RevoluPowered/one-voip-godot-4/releases/tag/v0.1

:3

**Comment by marc-weber1** [comment]
i think the linux version might just run now without issue after the 4.2 release so i added it in

**Comment by Pillber** [comment]
cool! is there some sort of timeline for when jitter buffers and threading will be completed? This project seems to have a lot of potential, but before this seems to have been stagnant for a little bit
