### ISSUE TITLE
Bad sound with 3+ clients

### ISSUE THREAD

**Issue by Nordup** [RevoluPowered/one-voip-godot-4#16]
Hey! I've been testing the plugin with my friends and seems like it's fine when 2 clients are talking
But when it comes to 3+ the voice pitch becomes very robotic and a lot of noise introduces
You can reproduce this with running 3 instances in godot

Do you know anything on this? Can I fix it somehow?
I've tried various bitrates and changing buffer length, no luck :(

PS. Fix is to set AudioStreamVOIP as local to scene #17

**Comment by Nordup** [comment]
It happens even when talking one at the time, meaning only one sends audio packets
And somehow if I set playing=false to one of the AudioStreamPlayer's with AudioStreamVOIP everything becomes normal

**Comment by Nordup** [comment]
Maybe I set up something wrong, but it’s unlikely) if it will be useful here is my project:
https://github.com/Nordup/thegatesjam
Uploading 5203037562170398562.mp4…

**Comment by Nordup** [comment]
Maybe I set up something wrong, but it’s unlikely) if it will be useful here is my project:
https://github.com/Nordup/thegatesjam
https://github.com/RevoluPowered/one-voip-godot-4/assets/54914954/bd6fffee-615b-4584-8081-914815ab2721

**Comment by Jakob-PB** [comment]
Sounds like this could possibly be related to https://github.com/godotengine/godot/issues/75109 if you are testing on Windows.

**Comment by Nordup** [comment]
doesn't seem like it actually)) it happens on linux and not related to files
