### ISSUE TITLE
Audio Stream VOIP doesn't instantiate playback

### ISSUE THREAD

**Issue by Johannled** [RevoluPowered/one-voip-godot-4#9]
I have tried implementing this in my Godot project using (version 4.2 stable) but I can't get it to work. When I press play, I get an error saying that the Audio Stream VOIP must implement the "instantiate playback" method. 

Here is the error:
```
E 0:00:05:0557   instantiate_playback: Method must be implemented!
  <C++ Error>    Method/function failed. Returning: Ref<AudioStreamPlayback>()
  <C++ Source>   servers/audio/audio_stream.cpp:187 @ instantiate_playback()
E 0:00:05:0557   play: Failed to instantiate playback.
  <C++ Error>    Condition "stream_playback.is_null()" is true.
  <C++ Source>   scene/3d/audio_stream_player_3d.cpp:580 @ play()

```

I'm very confused by this error since the method seems to be implemented at least from what I can tell. My guess is that I messed something up since I'm not very used to compiling C++ projects.

**Comment by Topicranger** [comment]
The godot_cpp submodule is outdated. You need to fetch the latest changes (`git submodule update --remote`) to compile for Godot 4.2 stable.

**Comment by Johannled** [comment]
That did indeed solve it!
